### ISSUE TITLE
New docs: Check if action is required and raise issues if necessary

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1142]
Based on the update in https://github.com/zwave-js/node-zwave-js/pull/1140#issue-525732829, the following changes potentially require some action:

### Application Command Class Specification

- [x] Added a clarification in Report more field in Extended User Code Get Command
- [x] Updated the Value interpretation in the Binary Switch Command Class
- [x] Clarified how to encode volume in the Sound Switch Tone Play Report (PR #1170)
- [x] Added a Multi Channel Consideration section for Command Classes that should only be supported at the root device
- [x] Clarified a field dependency in the Sound Switch Tone Play Report Command (PR #1170)
- [x] Removed a table reference error in Notification Command Class
- [x] Fixed maximum lock timeout in minute value.
- [x] Clarified what scale to apply when a supporting node reset the meter value. (#1171)

### Management Command Class Specification

- [x] Added Battery Command Class, version 3 (#1156)
- [x] Added Wake Up Command Class, version 3 (#1158)
- [x] Clarified the minimum granted firmware size that can be transferred using Firmware Update Meta Data Report Command
- [x] Added Indicator Command Class, version 4 (#1157)

### Transport Encapsulation Command Class Specification

- [x] Added a list of command classes that should only be supported by the Root Device of a Multi-Channel Device
- [x] Added Supervision Command Class, version 2 (#1158)
- [x] Added a new Authenticated / Unauthenticated ECDH key pair requirement (included in #1136)
- [x] Updated Supervision SessionID duplicate requirement, it now applies only for non-secure frames.
- [x] Updated the S0 Supported Commands Report to not contain non-secure Command Classes

### Command Class Control Specification

- [x] Updated the mandatory node interview of Version Command Class
- [x] Updated the Multi Channel Command Class mandatory interview figure
- [x] Added a recommendation to accept Wake Up Notifications using the same Supervision SessionID.
- [x] Clarified the generic control requirements about commands versions.
- [x] Clarified mandatory interview and supported scales for Meter Command Class
- [x] Made Multilevel Switch Supported Get optional for the node interview
