### ISSUE TITLE
Implement Battery CC V3

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1156]
Battery CC V3 adds a single field to the Battery Report command:
https://github.com/zwave-js/node-zwave-js/blob/master/specs/SDS13782%20Z-Wave%20Management%20Command%20Class%20Specification.pdf

**TODOs:**
- [x] Parse the new field
- [x] Include it in logging
- [x] update `@implementedVersion` decorator

**Comment by varet80** [comment]
I will try this as my first change! I already created a [battery-v3 branch](/zwave-js/node-zwave-js/tree/cc/battery-v3)
