### ISSUE TITLE
Support Indicator CC V4

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1157]
Indicator CC V4 adds two new commands:
* Indicator Description Get Command
* Indicator Description Report Command

https://github.com/zwave-js/node-zwave-js/blob/master/specs/SDS13782%20Z-Wave%20Management%20Command%20Class%20Specification.pdf

**TODOs:**
- [x] Implement the new commands
- [x] Implement a `getDescription` method on `IndicatorCCAPI`
- [x] update `@implementedVersion` decorator

**Comment by maverick1872** [comment]
Updated link to documentation can be found [here](https://github.com/zwave-js/specs/blob/0c0a0f9be2ff58330784c1888a4df07c4ac33804/SDS13782%20Z-Wave%20Management%20Command%20Class%20Specification.pdf).

**Comment by Reedham20** [comment]
Hey, I am new to open source and found this issue can I get any status updates on it. Any help is Highly appreciated
