### ISSUE TITLE
Add meta information for values

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#221]
this includes:
* type of the value
* min/max/allowed value(s)
* description
* readability/writability
* correctly capitalized name (`Interview completed` instead of `interviewCompleted`)

TODOs:
- [x] support for static description of the properties
- [x] support for dynamic update of the metadata
- [x] storing and loading dynamic metadata from the cache
