### ISSUE TITLE
[Tracking] Implement `toLogEntry` in all CCs and their subclasses

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#54]
current implementation status:

- [x] AlarmSensorCCGet
- [x] AlarmSensorCCReport
- [x] AlarmSensorCCSupportedGet _(empty CC)_
- [x] AlarmSensorCCSupportedReport
- [x] ApplicationStatusCCBusy
- [ ] ApplicationStatusCCRejectedRequest
- [x] AssociationCCGet
- [x] AssociationCCRemove
- [x] AssociationCCReport
- [x] AssociationCCSet
- [x] AssociationCCSpecificGroupGet _(empty CC)_
- [x] AssociationCCSpecificGroupReport
- [x] AssociationCCSupportedGroupingsGet _(empty CC)_
- [x] AssociationCCSupportedGroupingsReport
- [x] AssociationGroupInfoCCCommandListGet
- [x] AssociationGroupInfoCCCommandListReport
- [x] AssociationGroupInfoCCInfoGet
- [x] AssociationGroupInfoCCInfoReport
- [x] AssociationGroupInfoCCNameGet
- [x] AssociationGroupInfoCCNameReport
- [x] BarrierOperatorCCEventSignalingGet
- [x] BarrierOperatorCCEventSignalingReport
- [x] BarrierOperatorCCEventSignalingSet
- [x] BarrierOperatorCCGet _(empty CC)_
- [x] BarrierOperatorCCReport
- [x] BarrierOperatorCCSet
- [x] BarrierOperatorCCSignalingCapabilitiesGet _(empty CC)_
- [x] BarrierOperatorCCSignalingCapabilitiesReport
- [x] BasicCCGet _(empty CC)_
- [x] BasicCCReport
- [x] BasicCCSet
- [x] BasicWindowCoveringCCStartLevelChange
- [x] BasicWindowCoveringCCStopLevelChange _(empty CC)_
- [x] BatteryCCGet _(empty CC)_
- [x] BatteryCCHealthGet _(empty CC)_
- [x] BatteryCCHealthReport
- [x] BatteryCCReport
- [x] BinarySensorCCGet
- [x] BinarySensorCCReport
- [x] BinarySensorCCSupportedGet _(empty CC)_
- [x] BinarySensorCCSupportedReport
- [x] BinarySwitchCCGet _(empty CC)_
- [x] BinarySwitchCCReport
- [x] BinarySwitchCCSet
- [x] CRC16CCCommandEncapsulation
- [x] CentralSceneCCConfigurationGet _(empty CC)_
- [x] CentralSceneCCConfigurationReport
- [x] CentralSceneCCConfigurationSet
- [x] CentralSceneCCNotification
- [x] CentralSceneCCSupportedGet _(empty CC)_
- [x] CentralSceneCCSupportedReport
- [x] ClimateControlScheduleCCChangedGet _(empty CC)_
- [x] ClimateControlScheduleCCChangedReport
- [x] ClimateControlScheduleCCGet
- [x] ClimateControlScheduleCCOverrideGet _(empty CC)_
- [x] ClimateControlScheduleCCOverrideReport
- [x] ClimateControlScheduleCCOverrideSet
- [x] ClimateControlScheduleCCReport
- [x] ClimateControlScheduleCCSet
- [x] ClockCCGet _(empty CC)_
- [x] ClockCCReport
- [x] ClockCCSet
- [x] ColorSwitchCCGet
- [x] ColorSwitchCCReport
- [x] ColorSwitchCCSet
- [x] ColorSwitchCCStartLevelChange
- [x] ColorSwitchCCStopLevelChange
- [x] ColorSwitchCCSupportedGet _(empty CC)_
- [x] ColorSwitchCCSupportedReport
- [x] ConfigurationCCBulkGet
- [x] ConfigurationCCBulkReport
- [x] ConfigurationCCBulkSet
- [x] ConfigurationCCDefaultReset _(empty CC)_
- [x] ConfigurationCCError **(constructor only)**
- [x] ConfigurationCCGet
- [x] ConfigurationCCInfoGet
- [x] ConfigurationCCInfoReport
- [x] ConfigurationCCNameGet
- [x] ConfigurationCCNameReport
- [x] ConfigurationCCPropertiesGet
- [x] ConfigurationCCPropertiesReport
- [x] ConfigurationCCReport
- [x] ConfigurationCCSet
- [x] DeviceResetLocallyCCNotification _(ignored with comment)_
- [x] DoorLockCCCapabilitiesGet _(empty CC)_
- [x] DoorLockCCCapabilitiesReport
- [x] DoorLockCCConfigurationGet _(empty CC)_
- [x] DoorLockCCConfigurationReport
- [x] DoorLockCCConfigurationSet
- [x] DoorLockCCOperationGet _(empty CC)_
- [x] DoorLockCCOperationReport
- [x] DoorLockCCOperationSet
- [x] DoorLockLoggingCCRecordGet
- [x] DoorLockLoggingCCRecordReport
- [x] DoorLockLoggingCCRecordsSupportedGet _(empty CC)_
- [x] DoorLockLoggingCCRecordsSupportedReport
- [x] EnergyProductionCCGet
- [x] EnergyProductionCCReport
- [x] EntryControlCCConfigurationGet _(empty CC)_
- [x] EntryControlCCConfigurationReport
- [x] EntryControlCCConfigurationSet
- [x] EntryControlCCEventSupportedGet _(empty CC)_
- [x] EntryControlCCEventSupportedReport
- [x] EntryControlCCKeySupportedGet _(empty CC)_
- [x] EntryControlCCKeySupportedReport
- [x] EntryControlCCNotification
- [x] FibaroVenetianBlindCCGet _(ignored with comment)_
- [x] FibaroVenetianBlindCCReport
- [x] FibaroVenetianBlindCCSet
- [x] FirmwareUpdateMetaDataCCActivationReport
- [x] FirmwareUpdateMetaDataCCActivationSet
- [x] FirmwareUpdateMetaDataCCGet
- [x] FirmwareUpdateMetaDataCCMetaDataGet _(empty CC)_
- [x] FirmwareUpdateMetaDataCCMetaDataReport
- [x] FirmwareUpdateMetaDataCCPrepareGet
- [x] FirmwareUpdateMetaDataCCPrepareReport
- [x] FirmwareUpdateMetaDataCCReport
- [x] FirmwareUpdateMetaDataCCRequestGet
- [x] FirmwareUpdateMetaDataCCRequestReport
- [x] FirmwareUpdateMetaDataCCStatusReport
- [x] HumidityControlModeCCGet _(empty CC)_
- [x] HumidityControlModeCCReport
- [x] HumidityControlModeCCSet
- [x] HumidityControlModeCCSupportedGet _(empty CC)_
- [x] HumidityControlModeCCSupportedReport
- [x] HumidityControlOperatingStateCCGet _(empty CC)_
- [x] HumidityControlOperatingStateCCReport
- [x] HumidityControlSetpointCCCapabilitiesGet
- [x] HumidityControlSetpointCCCapabilitiesReport
- [x] HumidityControlSetpointCCGet
- [x] HumidityControlSetpointCCReport
- [x] HumidityControlSetpointCCScaleSupportedGet
- [x] HumidityControlSetpointCCScaleSupportedReport
- [x] HumidityControlSetpointCCSet
- [x] HumidityControlSetpointCCSupportedGet _(empty CC)_
- [x] HumidityControlSetpointCCSupportedReport
- [x] InclusionControllerCCComplete
- [x] InclusionControllerCCInitiate
- [x] IndicatorCCDescriptionGet
- [x] IndicatorCCDescriptionReport
- [x] IndicatorCCGet
- [x] IndicatorCCReport
- [x] IndicatorCCSet
- [x] IndicatorCCSupportedGet
- [x] IndicatorCCSupportedReport
- [x] IrrigationCCSystemConfigGet _(empty CC)_
- [x] IrrigationCCSystemConfigReport
- [x] IrrigationCCSystemConfigSet
- [x] IrrigationCCSystemInfoGet _(empty CC)_
- [x] IrrigationCCSystemInfoReport
- [x] IrrigationCCSystemShutoff
- [x] IrrigationCCSystemStatusGet _(empty CC)_
- [x] IrrigationCCSystemStatusReport
- [x] IrrigationCCValveConfigGet
- [x] IrrigationCCValveConfigReport
- [x] IrrigationCCValveConfigSet
- [x] IrrigationCCValveInfoGet
- [x] IrrigationCCValveInfoReport
- [x] IrrigationCCValveRun
- [x] IrrigationCCValveTableGet
- [x] IrrigationCCValveTableReport
- [x] IrrigationCCValveTableRun
- [x] IrrigationCCValveTableSet
- [x] LanguageCCGet _(empty CC)_
- [x] LanguageCCReport
- [x] LanguageCCSet
- [x] LockCCGet _(empty CC)_
- [x] LockCCReport
- [x] LockCCSet
- [x] ManufacturerSpecificCCDeviceSpecificGet
- [x] ManufacturerSpecificCCDeviceSpecificReport
- [x] ManufacturerSpecificCCGet _(empty CC)_
- [x] ManufacturerSpecificCCReport
- [x] MeterCCGet
- [x] MeterCCReport
- [x] MeterCCReset
- [x] MeterCCSupportedGet _(empty CC)_
- [x] MeterCCSupportedReport
- [x] MultiChannelAssociationCCGet
- [x] MultiChannelAssociationCCRemove
- [x] MultiChannelAssociationCCReport
- [x] MultiChannelAssociationCCSet
- [x] MultiChannelAssociationCCSupportedGroupingsGet _(empty CC)_
- [x] MultiChannelAssociationCCSupportedGroupingsReport
- [x] MultiChannelCCAggregatedMembersGet
- [x] MultiChannelCCAggregatedMembersReport
- [x] MultiChannelCCCapabilityGet
- [x] MultiChannelCCCapabilityReport
- [x] MultiChannelCCCommandEncapsulation
- [x] MultiChannelCCEndPointFind
- [x] MultiChannelCCEndPointFindReport
- [x] MultiChannelCCEndPointGet _(empty CC)_
- [x] MultiChannelCCEndPointReport
- [x] MultiChannelCCV1CommandEncapsulation
- [x] MultiChannelCCV1Get
- [x] MultiChannelCCV1Report
- [x] MultiCommandCCCommandEncapsulation
- [x] MultilevelSensorCCGet
- [x] MultilevelSensorCCGetSupportedScale
- [x] MultilevelSensorCCGetSupportedSensor _(empty CC)_
- [x] MultilevelSensorCCReport
- [x] MultilevelSensorCCSupportedScaleReport
- [x] MultilevelSensorCCSupportedSensorReport
- [x] MultilevelSwitchCCGet _(empty CC)_
- [x] MultilevelSwitchCCReport
- [x] MultilevelSwitchCCSet
- [x] MultilevelSwitchCCStartLevelChange
- [x] MultilevelSwitchCCStopLevelChange _(empty CC)_
- [x] MultilevelSwitchCCSupportedGet _(empty CC)_
- [x] MultilevelSwitchCCSupportedReport
- [x] NodeNamingAndLocationCCLocationGet _(empty CC)_
- [x] NodeNamingAndLocationCCLocationReport
- [x] NodeNamingAndLocationCCLocationSet
- [x] NodeNamingAndLocationCCNameGet _(empty CC)_
- [x] NodeNamingAndLocationCCNameReport
- [x] NodeNamingAndLocationCCNameSet
- [x] NotificationCCEventSupportedGet
- [x] NotificationCCEventSupportedReport
- [x] NotificationCCGet
- [x] NotificationCCReport
- [x] NotificationCCSet
- [x] NotificationCCSupportedGet _(empty CC)_
- [x] NotificationCCSupportedReport
- [x] PowerlevelCCGet _(empty CC)_
- [x] PowerlevelCCReport
- [x] PowerlevelCCSet
- [x] PowerlevelCCTestNodeGet _(empty CC)_
- [x] PowerlevelCCTestNodeReport
- [x] PowerlevelCCTestNodeSet
- [x] ProtectionCCExclusiveControlGet _(empty CC)_
- [x] ProtectionCCExclusiveControlReport
- [x] ProtectionCCExclusiveControlSet
- [x] ProtectionCCGet _(empty CC)_
- [x] ProtectionCCReport
- [x] ProtectionCCSet
- [x] ProtectionCCSupportedGet _(empty CC)_
- [x] ProtectionCCSupportedReport
- [x] ProtectionCCTimeoutGet _(empty CC)_
- [x] ProtectionCCTimeoutReport
- [x] ProtectionCCTimeoutSet
- [x] SceneActivationCCSet
- [x] SceneActuatorConfigurationCCGet
- [x] SceneActuatorConfigurationCCReport
- [x] SceneActuatorConfigurationCCSet
- [x] SceneControllerConfigurationCCGet
- [x] SceneControllerConfigurationCCReport
- [x] SceneControllerConfigurationCCSet
- [x] ScheduleEntryLockCCDailyRepeatingScheduleGet
- [x] ScheduleEntryLockCCDailyRepeatingScheduleReport
- [x] ScheduleEntryLockCCDailyRepeatingScheduleSet
- [x] ScheduleEntryLockCCEnableAllSet
- [x] ScheduleEntryLockCCEnableSet
- [x] ScheduleEntryLockCCSupportedGet _(empty CC)_
- [x] ScheduleEntryLockCCSupportedReport
- [x] ScheduleEntryLockCCTimeOffsetGet _(empty CC)_
- [x] ScheduleEntryLockCCTimeOffsetReport
- [x] ScheduleEntryLockCCTimeOffsetSet
- [x] ScheduleEntryLockCCWeekDayScheduleGet
- [x] ScheduleEntryLockCCWeekDayScheduleReport
- [x] ScheduleEntryLockCCWeekDayScheduleSet
- [x] ScheduleEntryLockCCYearDayScheduleGet
- [x] ScheduleEntryLockCCYearDayScheduleReport
- [x] ScheduleEntryLockCCYearDayScheduleSet
- [x] Security2CCCommandsSupportedGet _(empty CC)_
- [x] Security2CCCommandsSupportedReport
- [x] Security2CCKEXFail
- [x] Security2CCKEXGet _(empty CC)_
- [x] Security2CCKEXReport
- [x] Security2CCKEXSet
- [x] Security2CCMessageEncapsulation
- [x] Security2CCNetworkKeyGet
- [x] Security2CCNetworkKeyReport
- [x] Security2CCNetworkKeyVerify _(empty CC)_
- [x] Security2CCNonceGet
- [x] Security2CCNonceReport
- [x] Security2CCPublicKeyReport
- [x] Security2CCTransferEnd
- [x] SecurityCCCommandEncapsulation
- [x] SecurityCCCommandEncapsulationNonceGet _(empty CC)_
- [x] SecurityCCCommandsSupportedGet _(empty CC)_
- [x] SecurityCCCommandsSupportedReport
- [x] SecurityCCNetworkKeySet
- [x] SecurityCCNetworkKeyVerify _(empty CC)_
- [x] SecurityCCNonceGet _(empty CC)_
- [x] SecurityCCNonceReport
- [x] SecurityCCSchemeGet
- [x] SecurityCCSchemeInherit
- [x] SecurityCCSchemeReport
- [x] SoundSwitchCCConfigurationGet _(empty CC)_
- [x] SoundSwitchCCConfigurationReport
- [x] SoundSwitchCCConfigurationSet
- [x] SoundSwitchCCToneInfoGet
- [x] SoundSwitchCCToneInfoReport
- [x] SoundSwitchCCTonePlayGet _(empty CC)_
- [x] SoundSwitchCCTonePlayReport
- [x] SoundSwitchCCTonePlaySet
- [x] SoundSwitchCCTonesNumberGet _(empty CC)_
- [x] SoundSwitchCCTonesNumberReport
- [x] SupervisionCCGet
- [x] SupervisionCCReport
- [x] ThermostatFanModeCCGet _(empty CC)_
- [x] ThermostatFanModeCCReport
- [x] ThermostatFanModeCCSet
- [x] ThermostatFanModeCCSupportedGet _(empty CC)_
- [x] ThermostatFanModeCCSupportedReport
- [x] ThermostatFanStateCCGet _(empty CC)_
- [x] ThermostatFanStateCCReport
- [x] ThermostatModeCCGet _(empty CC)_
- [x] ThermostatModeCCReport
- [x] ThermostatModeCCSet
- [x] ThermostatModeCCSupportedGet _(empty CC)_
- [x] ThermostatModeCCSupportedReport
- [x] ThermostatOperatingStateCCGet _(empty CC)_
- [x] ThermostatOperatingStateCCLoggingGet
- [x] ThermostatOperatingStateCCLoggingReport
- [x] ThermostatOperatingStateCCLoggingSupportedGet _(empty CC)_
- [x] ThermostatOperatingStateCCLoggingSupportedReport
- [x] ThermostatOperatingStateCCReport
- [x] ThermostatSetbackCCGet _(empty CC)_
- [x] ThermostatSetbackCCReport
- [x] ThermostatSetbackCCSet
- [x] ThermostatSetpointCCCapabilitiesGet
- [x] ThermostatSetpointCCCapabilitiesReport
- [x] ThermostatSetpointCCGet
- [x] ThermostatSetpointCCReport
- [x] ThermostatSetpointCCSet
- [x] ThermostatSetpointCCSupportedGet _(empty CC)_
- [x] ThermostatSetpointCCSupportedReport
- [x] TimeCCDateGet _(empty CC)_
- [x] TimeCCDateReport
- [x] TimeCCTimeGet _(empty CC)_
- [x] TimeCCTimeOffsetGet _(empty CC)_
- [x] TimeCCTimeOffsetReport
- [x] TimeCCTimeOffsetSet
- [x] TimeCCTimeReport
- [x] TimeParametersCCGet _(empty CC)_
- [x] TimeParametersCCReport
- [x] TimeParametersCCSet
- [x] TransportServiceCCFirstSegment
- [x] TransportServiceCCSegmentComplete
- [x] TransportServiceCCSegmentRequest
- [x] TransportServiceCCSegmentWait
- [x] TransportServiceCCSubsequentSegment
- [x] UserCodeCCAdminCodeGet _(empty CC)_
- [x] UserCodeCCAdminCodeReport
- [x] UserCodeCCAdminCodeSet
- [x] UserCodeCCCapabilitiesGet _(empty CC)_
- [x] UserCodeCCCapabilitiesReport
- [x] UserCodeCCExtendedUserCodeGet
- [x] UserCodeCCExtendedUserCodeReport
- [x] UserCodeCCExtendedUserCodeSet
- [x] UserCodeCCGet
- [x] UserCodeCCKeypadModeGet _(empty CC)_
- [x] UserCodeCCKeypadModeReport
- [x] UserCodeCCKeypadModeSet
- [x] UserCodeCCReport
- [x] UserCodeCCSet
- [x] UserCodeCCUserCodeChecksumGet _(empty CC)_
- [x] UserCodeCCUserCodeChecksumReport
- [x] UserCodeCCUsersNumberGet _(empty CC)_
- [x] UserCodeCCUsersNumberReport
- [x] UserCredentialCCAdminPinCodeGet _(empty CC)_
- [x] UserCredentialCCAdminPinCodeReport
- [x] UserCredentialCCAdminPinCodeSet
- [x] UserCredentialCCAllUsersChecksumGet _(empty CC)_
- [x] UserCredentialCCAllUsersChecksumReport
- [x] UserCredentialCCAssociationReport
- [x] UserCredentialCCAssociationSet
- [x] UserCredentialCCCredentialCapabilitiesGet _(empty CC)_
- [x] UserCredentialCCCredentialCapabilitiesReport
- [x] UserCredentialCCCredentialChecksumGet
- [x] UserCredentialCCCredentialChecksumReport
- [x] UserCredentialCCCredentialGet
- [x] UserCredentialCCCredentialLearnCancel _(empty CC)_
- [x] UserCredentialCCCredentialLearnReport
- [x] UserCredentialCCCredentialLearnStart
- [x] UserCredentialCCCredentialReport
- [x] UserCredentialCCCredentialSet
- [x] UserCredentialCCKeyLockerCapabilitiesGet _(empty CC)_
- [x] UserCredentialCCKeyLockerCapabilitiesReport
- [x] UserCredentialCCKeyLockerEntryGet
- [x] UserCredentialCCKeyLockerEntryReport
- [x] UserCredentialCCKeyLockerEntrySet
- [x] UserCredentialCCUserCapabilitiesGet _(empty CC)_
- [x] UserCredentialCCUserCapabilitiesReport
- [x] UserCredentialCCUserChecksumGet
- [x] UserCredentialCCUserChecksumReport
- [x] UserCredentialCCUserGet
- [x] UserCredentialCCUserReport
- [x] UserCredentialCCUserSet
- [x] VersionCCCapabilitiesGet _(empty CC)_
- [x] VersionCCCapabilitiesReport
- [x] VersionCCCommandClassGet
- [x] VersionCCCommandClassReport
- [x] VersionCCGet _(empty CC)_
- [x] VersionCCReport
- [x] VersionCCZWaveSoftwareGet _(empty CC)_
- [x] VersionCCZWaveSoftwareReport
- [x] WakeUpCCIntervalCapabilitiesGet _(empty CC)_
- [x] WakeUpCCIntervalCapabilitiesReport
- [x] WakeUpCCIntervalGet _(empty CC)_
- [x] WakeUpCCIntervalReport
- [x] WakeUpCCIntervalSet
- [x] WakeUpCCNoMoreInformation _(empty CC)_
- [x] WakeUpCCWakeUpNotification _(empty CC)_
- [x] WindowCoveringCCGet
- [x] WindowCoveringCCReport
- [x] WindowCoveringCCSet
- [x] WindowCoveringCCStartLevelChange
- [x] WindowCoveringCCStopLevelChange
- [x] WindowCoveringCCSupportedGet _(empty CC)_
- [x] WindowCoveringCCSupportedReport
- [x] ZWavePlusCCGet _(empty CC)_
- [x] ZWavePlusCCReport

**Comment by AlCalzone** [comment]
The implementation can be generated with the `zwcclog` snippet. Any `toJSON` implementations can be deleted.
Some of the above entries are false positives, e.g. encapsulating CCs without any custom values or empty Get-type CCs.
