### ISSUE TITLE
Add statistics

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#985]
Things that should be considered (total and per node):

- [x] Transmitted messages per node (#2736)
- [x] Transmitted messages (controller) (#2736)
- [x] Received messages per node (#2736)
- [x] Received messages (controller) (#2736)
- [x] Dropped messages from nodes
- [x] Dropped messages from the controller (#2736)
- [x] Controller errors (CAN, NAK, timeout) (#2736)
- [ ] Node errors (NoACK, timeout, ...) (done in #2736, but currently no distinction between not sent and NoACK)
- [x] Response time (#4022)
- [x] Background RSSI, current and average (done in #5545)
- [ ] Failures during interview
- [x] When was a node last seen (alive/awake/unsolicited msg) (#6008)
- [ ] Queue: size, what is in the queue? (#1270)

**Comment by LordMike** [comment]
> Bonus to having events per message, rather than just counters, is also being able to see how long it actually took to deliver that "turn on" message. Would help immensely in tracking down where delays are occurring, when lights appear slow.

https://github.com/zwave-js/node-zwave-js/issues/1270#issuecomment-757505434

**Comment by nicoh88** [comment]
+1 for `last seen`

**Comment by jaimevisser** [comment]
Especially on bigger z-wave networks this would be a big help in tuning sensor data output.

**Comment by Masterz69** [comment]
Missing ```last seen``` property on Home Assistant for ZWave devices.

Just today had an situation: FGBS-222 was powered off for ~25 minutes.
Device is configured to report every 5 minutes, couple of messages not received by controller.
ZWAVEJS2MQTT device ```node status``` still ```alive``` :( 
- as no configuration on device level: when to declare device  to not ```alive``` when no messages received from.

IMHO I can't relay on ```node status``` to determine actual device status.
```last seen``` will help to react on devices sending no info long time.

**Comment by AlCalzone** [comment]
`lastSeen` will be added in https://github.com/zwave-js/node-zwave-js/pull/6008
